export const START_NEW_GAME = 'START_NEW_GAME';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const MOVE_SNAKE = 'MOVE_SNAKE';
export const HANDLE_GAME_INPUT = 'HANDLE_GAME_INPUT';
